"""fix creatad_at colomn in tables

Revision ID: a763f59bfeef
Revises: 9528bc2fd440
Create Date: 2025-07-01 14:17:53.969840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a763f59bfeef"
down_revision: Union[str, Sequence[str], None] = "9528bc2fd440"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
